# Configuration Netlify pour le site horizon-libre-site

[build]
  # Indique à Netlify le dossier à mettre en ligne.
  # La valeur "." signifie la racine de ton projet.
  # Si ton fichier index.html est dans un dossier "public" ou "dist",
  # tu devras remplacer "." par "public" ou "dist".
  publish = "."
