# Fichier : horizon-libre-site/netlify.toml
# Configuration pour un site simple en HTML/CSS/JS sans étape de build.

[build]
  # Indique à Netlify que le dossier à publier est la racine du projet.
  # Si ton fichier index.html est dans un autre dossier (comme "public"),
  # il faudra changer "." par "public".
  publish = "."
