# On dit à Netlify de ne lancer AUCUNE commande de build.
# Le bot a déjà fait tout le travail en amont.
[build]
  command = ""

# On dit à Netlify que le site à publier se trouve à la racine du dépôt.
[build.settings]
  publish = "/"

# On garde la version de Python au cas où nous ajouterions des fonctions serverless.
[build.environment]
  PYTHON_VERSION = "3.11"
